### PR TITLE
New layout

### PR DESCRIPTION
**Pull request by melissaroses**
I organized and renamed some files to better reflect standard web dev practice, and I redid the layout for the whole site so it's easier to scale and maintain.

### CODE REVIEW

**Review by aburrell — COMMENTED** [review]
It is looking good, except for one thing and I don't know how to fix it.  The text on the letter example page is smaller than the text everywhere else.  I included two screenshots so you can see what I see:

normal_size

small_size

**Comment by melissaroses** [comment]
I see the difference in your screenshots, but on my end it's consistent
across all pages. It almost looks like a different magnification from the
browser, but it seems to be fine from here, I'm not sure why it would do
that. Is it still doing it?

**Comment by aburrell** [comment]
Yes, in Chrome.  I also checked in Safari and the paragraph text is fine but the accordion text is too small.  Maybe there's something wrong in that?

**Review by aburrell — APPROVED** [review]
Approving based on discussion during meeting today.

**Pull request merged**
